---
  - name: supervisor | Installing required apt_packages
    apt:
      pkg=python-pip
      state=latest
      update_cache=yes

  - name: supervisor | Installing supervisor with pip
    pip:
      name=supervisor
      executable=pip3

  - name: supervisor | Copying Upstart script for supervisor
    template:
      src=supervisord_init.conf.j2
      dest=/etc/init/supervisord.conf
      owner=root
      mode=644
      backup=yes

  - name: supervisor | Creating directories
    file:
      path={{item}}
      owner=root
      state=directory
    with_items:
      - /etc/supervisor/conf.d
      - "{{supervisor_log_dir}}"

  - name: supervisor | Copying base configuration
    template:
      src=supervisord_base.conf.j2
      dest={{supervisor_config_dir}}/supervisord.conf

  - name: supervisor | Symlinking base configuration to /etc
    file:
      src={{supervisor_config_dir}}/supervisord.conf
      dest=/etc/supervisord.conf
      state=link
    notify:
      - restart supervisor

