---
  - name: oracle | Installing required apt packages
    apt:
      pkg={{item}}
      state=latest
      update_cache=yes
    with_items:
      - libaio1
      - libffi-dev
      - unzip
      
  - name: oracle | Download IC zips
    command:
      wget -nc {{oracle_ic_url}}{{item}}
      chdir=/tmp
    with_items:
      - "{{oracle_ic_basic}}"
      - "{{oracle_ic_sqlplus}}"
      - "{{oracle_ic_devel}}"

  - name: oracle | Creating IC main dir
    file:
       path="{{oracle_ic_dir}}"
       state=directory

  - name: oracle | Creating IC symlink
    file:
       src="{{oracle_ic_dir}}"
       dest="{{oracle_ic_symlink}}"
       state=link

  - name: oracle | Unzipping IC files
    unarchive:
      src="/tmp/{{item}}"
      dest="{{oracle_ic_dir}}"
      copy=no

    with_items:
      - "{{oracle_ic_basic}}"
      - "{{oracle_ic_sqlplus}}"
      - "{{oracle_ic_devel}}"

  - name: oracle | Adding Oracle libs to ld.so.conf.d
    lineinfile:
      dest=/etc/ld.so.conf.d/oracle.conf
      line="{{oracle_ic_symlink}}"
      state=present
      create=yes

  - name: oracle | Adding Oracle vars to system wide profile
    lineinfile:
      dest=/etc/profile
      line="export {{item}}={{oracle_home}}"
      state=present
    with_items:
      - LD_LIBRARY_PATH
      - TNS_ADMIN
      - ORACLE_HOME

  - name: oracle | Adding Oracle IC dir to PATH
    lineinfile:
      dest=/etc/profile
      line="export PATH=$PATH:{{oracle_home}}"
      state=present

  - name: oracle | Creating IC symlink
    file:
       src="{{oracle_ic_dir}}"
       dest="{{oracle_ic_symlink}}"
       state=link

  - name: oracle | Creating symlink para libclntsh.so
    file:
       src="{{oracle_ic_dir}}/libclntsh.so.11.1"
       dest="{{oracle_ic_dir}}/libclntsh.so"
       state=link

  - name: oracle | Creating symlink para libocci.so
    file:
       src="{{oracle_ic_dir}}/libocci.so.11.1"
       dest="{{oracle_ic_dir}}/libocci.so"
       state=link

  - name: oracle | Running ldconfig
    command:
      ldconfig
