- hosts: all
  roles:
#    - server-bootstrap
#    - apache
    - nginx
    - postgresql
    - supervisor
    - uwsgi
    - redis
    - memcached
    - java
    - elasticsearch
  vars:
    bootstrap_copy_publickey: false
    bootstrap_install_dev_packages: false
    bootstrap_local_sources: false
    bootstrap_locale: es_AR.UTF-8
    bootstrap_set_locale: false
    bootstrap_ufw_state: disabled
    remote_user: "{{ansible_ssh_user}}"
    memcached_set_fs_file_max: false
    redis_travis_ci: false
