- hosts: all
  roles:
    - server-bootstrap
    - apache
    - monit
    - nginx
    - postgresql
    - supervisor
    - uwsgi
    - memcached
  vars:
    remote_user_name: {{ansible_ssh_user}}
    bootstrap_locale: es_AR.UTF-8
    bootstrap_local_sources: false
    bootstrap_ufw_state: disabled
    bootstrap_install_dev_packages: false
