---
  - name: nginx | Adding repo key
    apt_key:
      url=http://nginx.org/keys/nginx_signing.key
      state=present
    
  - name: nginx | Adding nginx repository
    apt_repository:
      repo="{{nginx_repository}}"
      update_cache=yes
      state=present

  - name: nginx | Installing nginx
    apt:
      pkg=nginx

  - name: nginx | Creating ssl dir
    file:
      path=/etc/nginx/ssl
      state=directory
      owner=root
      mode=770

  - name: nginx | Creating sites-available dir
    file:
      path=/etc/nginx/sites-available
      state=directory
      owner=root
      mode=770

  - name: nginx | Creating sites-enabled dir
    file:
      path=/etc/nginx/sites-enabled
      state=directory
      owner=root
      mode=770

  - name: nginx | Copying nginx.conf
    template:
      src=nginx.conf.j2
      dest=/etc/nginx/nginx.conf
      backup=yes
      owner=root
      mode=0644
    notify:
      - restart nginx
