---
# tasks file for nginx
  - name: nginx | Adding nginx ppa
    apt_repository:
      repo="{{nginx_ppa}}"
      update_cache=yes
    when: nginx_install_from_ppa

  - name: nginx | Installing nginx
    apt:
      pkg=nginx

  - name: nginx | Copying nginx.conf
    template:
      src=nginx.conf.j2
      dest=/etc/nginx/nginx.conf
      backup=yes
      owner=root
      mode=0644
    notify:
      - restart nginx

  - name: nginx | Enabling monitoring with monit
    template:
      src=monit_nginx.j2
      dest=/etc/monit/conf.d/nginx
      backup=yes
      owner=root
      mode=0644
    when: monit_protection == true
    notify:
      - restart monit

