---
  - name: nginx | Adding nginx ppa stable
    apt_repository:
      repo="{{nginx_ppa_stable}}"
      update_cache=yes
    when: nginx_version == "stable"

  - name: nginx | Adding nginx ppa mainline
    apt_repository:
      repo="{{nginx_ppa_mainline}}"
      update_cache=yes
    when: nginx_version == "mainline"

  - name: nginx | Installing nginx
    apt:
      pkg=nginx

  - name: nginx | Creating ssl dir
    file:
      path=/etc/nginx/ssl
      state=directory
      owner=root
      mode=770

  - name: nginx | Copying nginx.conf
    template:
      src=nginx.conf.j2
      dest=/etc/nginx/nginx.conf
      backup=yes
      owner=root
      mode=0644
    notify:
      - restart nginx
