---
  - name: Ubuntu | Installing Docker engine
    apt:
      name=docker.io
      state=present
      update_cache=yes
    when: ansible_distribution == 'Ubuntu'

  - name: Ubuntu | Installing docker-compose
    pip:
      name=docker-compose
      state=latest

  - name: Ubuntu | Adding remote user to docker group
    user:
      name={{remote_user}}
      groups=docker
      append=yes
