---
# tasks file for uwsgi
  - name: Installing required apt packages
    apt:
      pkg={{item}}
      state=latest
      update_cache=yes
    with_items:
      - build-essential
      - python-dev
      - libpcre3
      - libpcre3-dev

  - name: Installing uwsgi
    pip:
      name={{item}}
    with_items:
      - uwsgi
      - uwsgitop

  - name: Creating directories
    file:
      path={{item}}
      state=directory
      mode=700
      owner=root
    with_items:
      - "{{uwsgi_log_directory}}"
      - "{{uwsgi_config_directory}}"
      - "{{uwsgi_apps_available_dir}}"
      - "{{uwsgi_apps_enabled_dir}}"

  - name: Copying uwsgi base config
    template:
      src=uwsgi.ini.j2
      dest={{uwsgi_config_directory}}/{{uwsgi_config_file}}
      owner=root
      mode=644
      backup=yes
    notify:
      - start uwsgi

