---
# tasks file for uwsgi
  - name: uWSGI | Installing required apt packages
    apt:
      pkg={{item}}
      state=latest
      update_cache=yes
    with_items:
      - build-essential
      - python-dev
      - libpcre3
      - libpcre3-dev

  - name: uWSGI | Installing uwsgi
    pip:
      name=uwsgi

  - name: uWSGI | Creating directories
    file:
      path={{item}}
      state=directory
      mode=700
      owner=root
    with_items:
      - "{{uwsgi_log_directory}}"
      - "{{uwsgi_config_directory}}"
      - "{{uwsgi_apps_available_dir}}"
      - "{{uwsgi_apps_enabled_dir}}"

  - name: uWSGI | Copying upstart file
    template:
      src=uwsgi_upstart.conf
      dest=/etc/init/{{uwsgi_service_name}}.conf
      owner=root
      mode=644
      backup=yes

  - name: uWSGI | Copying uwsgi base config
    template:
      src=uwsgi.ini
      dest={{uwsgi_config_directory}}/{{uwsgi_config_file}}
      owner=root
      mode=644
      backup=yes
    notify:
      - start uwsgi

