---
  - name: Installing required packages (Ubuntu)
    apt:
      state: latest
      update_cache: yes
      name:
        - build-essential
        - python-dev
        - libpcre3
        - libpcre3-dev
    when: ansible_distribution == 'Ubuntu'

  - name: Installing required packages python3 (Ubuntu)
    apt:
      state: latest
      update_cache: yes
      name:
        - python3
        - python3-setuptools
        - python3-pip
    when:
      - ansible_distribution == 'Ubuntu'

  - name: Installing uwsgi python3
    pip:
      name:
        - uwsgi
        - uwsgitop
      executable: pip3

  - name: Creating directories
    file:
      path={{item}}
      state=directory
      mode=700
      owner=root
    with_items:
      - "{{uwsgi_log_directory}}"
      - "{{uwsgi_config_directory}}"
      - "{{uwsgi_apps_available_dir}}"
      - "{{uwsgi_apps_enabled_dir}}"
    when: ansible_distribution == 'Ubuntu'

  - name: Copying uwsgi base config
    template:
      src=uwsgi.ini.j2
      dest={{uwsgi_config_directory}}/{{uwsgi_config_file}}
      owner=root
      mode=644
      backup=yes
    when: ansible_distribution == 'Ubuntu'

  - name: Add uwsgi systemd unit file
    become: yes
    template:
        src: uwsgi_systemd.service.j2
        dest: "/etc/systemd/system/{{uwsgi_service_name}}.service"
    when: uwsgi_systemd == true

  - name: Enable and start uwsgi systemd
    become: yes
    service:
      name: "{{uwsgi_service_name}}.service"
      enabled: yes
      state: started
    when: uwsgi_systemd == true
