---
# handlers file for uwsgi

- name: restart uwsgi
  service:
    name: "{{uwsgi_service_name}}"
    state: restarted

- name: start uwsgi
  service:
    name: "{{uwsgi_service_name}}"
    state: started
