---
# tasks file for apache

  - name: apache | Installing packages
    apt:
      pkg={{item}}
      state=latest
      update_cache=yes
    with_items:
      - apache2
      - apache2-utils
    when: ansible_os_family == "Debian"

  - name: apache | Installing mod-wsgi
    apt:
      pkg=libapache2-mod-wsgi
      state=latest
      update_cache=no
    when: apache_install_mod-wsgi
    when: ansible_os_family == "Debian"

  - name: apache | Disabling default mpm module
    command: a2dismod mpm_event
    when: ansible_os_family == "Debian"

  - name: apache | Enabling preferred mpm module
    command: a2enmod mpm_{{apache_mpm}}
    when: ansible_os_family == "Debian"

  - name: apache | Installing mod-proxy-uwsgi
    apt:
      pkg=libapache2-mod-proxy-uwsgi
      state=latest
      update_cache=no
    when: apache_install_mod_proxy_uwsgi
    when: ansible_os_family == "Debian"

  - name: apache | Enabling mod-proxy-uwgi
    command: a2enmod {{item}}
    with_items:
      - proxy
      - proxy_uwsgi
    when: apache_install_mod_proxy_uwsgi
    when: ansible_os_family == "Debian"

  - name: apache | Installing packages
    yum:
      pkg={{item}}
      state=latest
      update_cache=yes
    with_items:
      - httpd
      - "{{apache_mpm}}"
      - apache2-utils
    when: ansible_os_family == "RedHat"

  - name: apache | Installing mod-wsgi
    apt:
      pkg=libapache2-mod-wsgi
      state=latest
      update_cache=no
    when: apache_install_mod-wsgi
    when: ansible_os_family == "RedHat"

  - name: apache | Adding localhost directive to apache2.conf
    lineinfile:
      dest=/etc/apache2/apache2.conf
      line="ServerName localhost"
      state=present

  - name: apache | Creating ssl dir in /etc/apache2
    file:
      path=/etc/apache2/ssl
      owner=root
      group=root
      state=directory

  - name: apache | Enabling apache2 modules
    command: a2enmod {{item}}
    with_items: apache_modules

  - name: apache | Enabling monitoring with monit
    template:
      src=monit_apache.j2
      dest=/etc/monit/monitrc.d/apache
      backup=yes
      owner=root
      mode=0644
    when: apache_enable_monit
    notify:
      - restart monit

  - name: apache | Setting ServerToken
    lineinfile:
      dest=/etc/apache2/conf-available/security.conf
      regexp=^ServerTokens
      line="ServerTokens {{apache_server_tokens}}"

  - name: apache | Setting ServerSignature
    lineinfile:
      dest=/etc/apache2/conf-available/security.conf
      regexp=^ServerSignature
      line="ServerSignature {{apache_server_signature}}"

