---
  - name: Installing packages
    apt:
      pkg={{item}}
      state=latest
      update_cache=yes
    with_items:
      - apache2
      - apache2-utils
      - apache2-mpm-{{apache_mpm}}
    when: ansible_os_family == "Debian"

  - name: Installing mod-wsgi
    apt:
      pkg=libapache2-mod-wsgi
      state=latest
      update_cache=no
    when: apache_install_mod-wsgi is defined and ansible_os_family == "Debian"

  - name: Disabling default mpm module
    command: a2dismod mpm_event
    when: ansible_os_family == "Debian"

  - name: Enabling preferred mpm module
    command: a2enmod mpm_{{apache_mpm}}
    when: ansible_os_family == "Debian"

  - name: Installing mod-proxy-uwsgi
    apt:
      pkg=libapache2-mod-proxy-uwsgi
      state=latest
      update_cache=no
    when: apache_install_mod_proxy_uwsgi is defined and ansible_os_family == "Debian"

  - name: Enabling mod-proxy-uwgi
    command: a2enmod {{item}}
    with_items:
      - proxy
      - proxy_uwsgi
    when: apache_install_mod_proxy_uwsgi is defined and ansible_os_family == "Debian"

  - name: Installing packages
    yum:
      pkg={{item}}
      state=latest
      update_cache=yes
    with_items:
      - httpd
      - "{{apache_mpm}}"
      - apache2-utils
    when: ansible_os_family == "RedHat"

  - name: Installing mod-wsgi
    apt:
      pkg=libapache2-mod-wsgi
      state=latest
      update_cache=no
    when: apache_install_mod-wsgi is defined and ansible_os_family == "RedHat"

  - name: Adding localhost directive to apache2.conf
    lineinfile:
      dest=/etc/apache2/apache2.conf
      line="ServerName localhost"
      state=present

  - name: Creating ssl dir in /etc/apache2
    file:
      path=/etc/apache2/ssl
      owner=root
      group=root
      state=directory

  - name: Enabling apache2 modules
    command: a2enmod {{item}}
    with_items: apache_modules

  - name: Setting ServerToken
    lineinfile:
      dest=/etc/apache2/conf-available/security.conf
      regexp=^ServerTokens
      line="ServerTokens {{apache_server_tokens}}"

  - name: Setting ServerSignature
    lineinfile:
      dest=/etc/apache2/conf-available/security.conf
      regexp=^ServerSignature
      line="ServerSignature {{apache_server_signature}}"

