- name: Ubuntu | Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items: ["python-psycopg2", "python-pycurl"]
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu | Add PostgreSQL repository apt-key
  apt_key:
    id: ACCC4CF8
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu | Add PostgreSQL repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main {{postgresql_version}}'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu | Install PostgreSQL
  apt:
    name: "{{item}}"
    state: present
  environment:
    LC_ALL: "{{ postgresql_locale }}"
    LC_LCTYPE: "{{ postgresql_locale }}"
  with_items:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
  when: ansible_distribution == 'Ubuntu'

- name: FreeBSD | Install PostgreSQL
  pkgng:
    pkg: "{{item}}"
    state: present
  environment:
    LC_ALL: "{{ postgresql_locale }}"
    LC_LCTYPE: "{{ postgresql_locale }}"
  with_items:
    - "postgresql{{postgresql_freebsd_version}}-server"
    - "postgresql{{postgresql_freebsd_version}}-client"
  when: ansible_distribution == 'FreeBSD'

- name: FreeBSD | Enabling postgresql service
  lineinfile:
    dest=/etc/rc.conf
    line="postgresql_enable='YES'"
    state=present
  when: ansible_distribution == 'FreeBSD'

- name: FreeBSD | Make sure the dependencies are installed
  pkgng:
    pkg: "{{item}}"
    state: present
  with_items: ["py27-pycurl"]
  when: ansible_distribution == 'FreeBSD'

- name: FreeBSD | Installing psycopg2
  pip:
    name: psycopg2
    state: present
  when: ansible_distribution == 'FreeBSD'
