# file: postgresql/tasks/main.yml

- import_tasks: install.yml
- import_tasks: extensions.yml
- import_tasks: configure.yml
- import_tasks: databases.yml
- import_tasks: users.yml
- import_tasks: pgbouncer.yml
  when: postgresql_install_pgbouncer == true
