---
# Install elasticsearch

- name: elasticsearch | Adding ES repository key
- apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: elasticsearch | Adding ES repository
- apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/{{ es_version }}/debian stable main' state=present

- name: elasticsearch | Installing ES
  apt: name={{ item }} state=latest force=yes
  tags: elasticsearch
  with_items:
    - elasticsearch
  notify: init elasticsearch

- name: elasticsearch | Tuning limits.conf
  lineinfile: dest=/etc/security/limits.conf line="{{ item }}"
  tags: elasticsearch
  with_items:
    - 'elasticsearch soft nofile 32000'
    - 'elasticsearch hard nofile 32000'

- name: elasticsearch | Ensuring the service is started
- service: name=elasticsearch state=started

- name: elasticsearch | Installing plugins
- include: plugins.yml
