---
- name: Check if ES is already installed
  command: dpkg-query -W elasticsearch
  register: elasticsearch_check_deb
  failed_when: elasticsearch_check_deb.rc > 1
  changed_when: elasticsearch_check_deb.rc == 1

- name: Download ES
  get_url: 
    url="{{ es_download_url }}"
    dest="/tmp/{{es_deb_package}}"
  when: elasticsearch_check_deb

- name: Installing ES
  apt:
    deb="/tmp/{{es_deb_package}}"
  when: elasticsearch_check_deb

- name: Ensuring the service is started
  service:
    name=elasticsearch
    state=started

- name: Installing plugins
  import_tasks: plugins.yml

- name: Copy configuration template
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    backup: yes

- name: Copy default values
  template:
    src: elasticsearch_defaults.j2
    dest: /etc/default/elasticsearch
    backup: no

- name: Restarting service
  service:
    name=elasticsearch
    state=restarted
