---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Instancia con systemd para que funcionen los handlers del rol
  # https://molecule.readthedocs.io/en/latest/examples.html#systemd-container
  - name: instance
    image: docker.io/ubuntu:16.04
    pre_build_image: false
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #capabilities:
      #- SYS_ADMIN
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  #inventory:
    #host_vars:
      ## setting for the platform instance named 'instance'
      #instance:
        #ansible_user: ansible
  lint:
      name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
scenario:
  name: default
  test_sequence:
    #- lint
    - destroy
    #- dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    #- side_effect
    - verify
    - destroy
