# file: postgresql/tasks/extensions/dev_headers.yml

- name: PostgreSQL | Extensions | Make sure the development headers are installed
  apt:
    name: libpq-dev
    state: present
  notify:
    - restart postgresql
  when: ansible_distribution == 'Ubuntu'

- name: PostgreSQL | Extensions | Make sure the development headers are installed
  yum:
    name: libpqxx-devel
    state: present
  notify:
    - restart postgresql
  when: ansible_distribution == 'Amazon'
