# file: postgresql/tasks/extensions/postgis.yml

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed
  apt:
    name: "{{packages}}"
    state: present
  vars:
    packages:
      - libgeos-c1*
      - "postgresql-{{postgresql_version}}-postgis-{{postgresql_ext_postgis_version}}"
  notify:
    - restart postgresql
  when: ansible_distribution == 'Ubuntu'
