---
  - name: redis | Adding redis PPA
    apt_repository:
      repo={{redis_ppa}}
      state=present

  - name: redis | Installing redis
    apt:
      name=redis-server
      update_cache=yes
      state=present
    notify:
      - restart redis