---
  - name: redis | Adding redis PPA
    apt_repository:
      repo={{redis_ppa}}
      state=present
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'xenial'

  - name: redis | Installing redis
    apt:
      name=redis-server
      update_cache=yes
      state=present
    notify:
      - restart redis
    when: ansible_distribution == 'Ubuntu'

  - name: redis | Installing redis
    pkgng:
      pkg=redis
      state=present
    when: ansible_distribution == 'FreeBSD'

  - name: redis | Adding a second instance:configuration
    template:
      src=redis_secondary.conf.j2
      dest=/etc/redis/redis_secondary.conf
      backup=yes
    when: redis_secondary_master == true

  - name: redis | Adding a second instance:cache directory
    file:
      path=/var/lib/redis-secondary
      state=directory
      owner=redis
      group=redis
    when: redis_secondary_master == true

  - name: redis | Adding a second instance:init script
    template:
      src=redis-secondary-server
      dest=/etc/init.d/redis-secondary-server
      backup=no
      mode=0755
    when: redis_secondary_master == true

  - name: redis | Adding a second instance:starting on boot
    shell: update-rc.d redis-secondary-server defaults
    when: redis_secondary_master == true

  - name: redis | Adding a second instance:starting service now
    service:
      name=redis-secondary-server
      state=started
    when: redis_secondary_master == true

  - name: Enabling redis service (FreeBSD)
    lineinfile:
      dest=/etc/rc.conf
      line="redis_enable='YES'"
      state=present
    when: ansible_distribution == 'FreeBSD'

  - name: Start redis (FreeBSD)
    service:
      name: redis
      state: started
    when: ansible_distribution == 'FreeBSD'
